rutas:
  base: "."
  
  # Carpetas principales
  carpetas:
    data: "./Data"
    notebooks: "./notebooks"
    outputs: "./outputs"
    reports: "./reports"
  
  # Subcarpetas de Data
  data:
    raw: "./Data/raw"
    cleaned: "./Data/cleaned"
    mappings: "./Data/mappings"
  
  # Archivos específicos por categoría
  archivos:
    raw:
      datos_crudos: "./Data/raw/"
    
    cleaned:
      exportaciones: "./Data/cleaned/exportaciones.csv"
      data: "./Data/cleaned/expo_unificadas.csv"
    
    mappings:
      paises: "./Data/mappings/paises.csv"
      vias: "./Data/mappings/vias.csv"
      departamentos: "./Data/mappings/departamentos.csv"

parametros:
  encoding: "utf-8-sig"
  separador: ","
  valor_no_declarado: "No Declarado"